### ISSUE TITLE
the `align: center` setting is not respected for images

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockstor-doc#311]
We set the alignment for images using the `align: center` setting but this setting is not applied. For instance, the following block...
```rst
.. image:: /images/installation/install/update-arrow.png
   :align: center
```
... results in:
![image](https://user-images.githubusercontent.com/30297881/135162351-fd2e176c-eec2-4494-a3e2-14ad59c06396.png)

Upon inspection of the related HTML block, we can see that the style was correctly applied:
```html
<img alt="../_images/update-arrow.png" class="align-center" src="../_images/update-arrow.png">
```

What is missing is actually the definition of the `align-center` class in our css stylesheet.

It is thus proposed to add such definition in our stylesheet by copying its current definition in the sphinx *style* that we currently inherit from:
```css
img.align-center, figure.align-center, .figure.align-center, object.align-center {
  display: block;
  margin-left: auto;
  margin-right: auto;
}
```
https://github.com/sphinx-doc/sphinx/blob/9e1b4a8f1678e26670d34765e74edf3a3be3c62c/sphinx/themes/basic/static/basic.css_t#L292-L296
